### PR TITLE
Update to work with current version of pikepdf, pypdf2

### PR DESCRIPTION
**Pull request by kaieberl**
- update code
- create requirements.txt

### CODE REVIEW

**Review by SkyeC0re — CHANGES_REQUESTED** [review]
Functionality looks good, just remove the requirements in the readme as well.

**Comment by kaieberl** [comment]
Done.

**Comment by SkyeC0re** [comment]
Awesome, LGTM :fire:

**Comment by SkyeC0re** [comment]
Sorry just realized you forced pushed some of your modifications away, Ill add them back in, its on me for not spotting in the review now

**Comment by kaieberl** [comment]
Sorry for that. I put those changes in the `replace-original-file` branch

**Pull request merged**
